spring:
  flyway:
    schemas: forum_post
    default-schema: forum_post
    locations:
      - classpath:db/migration/dev
      - classpath:db/migration/ddl
      - classpath:db/migration/dml
      - classpath:db/migration/procedures
      - classpath:db/migration/views

