package com.example.forumserver.core.configuration

val PROMOTE_USER_PERMISSION = "PROMOTE_USER_PERMISSION"
val POST_PERMISSION = "POST_PERMISSION"
val THREAD_PARENT_PERMISSION = "THREAD_PARENT_PERMISSION"
val THREAD_CHILD_PERMISSION = "THREAD_CHILD_PERMISSION"